fix fatal PHP error
I get this error message.

Fatal error: Call to undefined function tx_simplemvc_model_convertForName() in /home/path/public_html/developer/typo3conf/ext/simplemvc/Classes/Model/AbstractModel.php(819) : regexp code on line 1 

Use preg_replace_callback instead of preg_replace and the deprecated "e" regular expression option.
The method tx_simplemvc_model_convertForName shall be inside of the class.